version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: certbot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
