deployment:
  admin:
    admin_key_required: true
    admin_key:
      - name: admin
        key: BTLvdLB6XptSridgdmuV
        role: admin
    allow_admin:
      - 0.0.0.0/0
    admin_listen:
      ip: 0.0.0.0
      port: 9180
  etcd:
    host:
      - http://etcd:2379

apisix:
  node_listen: 9080
  enable_admin: true
  enable_control: true
  # Set the control port to a different value
  control:
    ip: "0.0.0.0"
    port: 9190
  ssl:
    enable: true
    listen_port: 9443
